version: '3'

services:
  backend:
    container_name: backend_api_java
    image: myapps/api-java
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      - "PORT=8081"
    ports:
      - 8081:8081
  
  postgres:
    container_name: postgres_db
    image: postgres:15.0
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgresdb"
      - "TZ=America/Sao_Paulo"
    ports:
      - 5432:5432
    volumes:
    - ./data:/var/lib/postgresql/data
