server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
app:
  security:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: ${JWT_EXPIRATION_MS}
    public-routes: ${PUBLIC_ROUTES}

logging:
  level:
    root: INFO
