version: '3'

services:
  market_db:
    container_name: market-db
    image: postgres:14
    environment:
      - "POSTGRES_DB=market"
      - "POSTGRES_USER=market"
      - "POSTGRES_PASSWORD=market"
      # - "POSTGRES_USER=${VAR_NAME:-market}"
    ports:
      - 5432:5432
    healthcheck:
      # test: psql --echo-all --username ${VAR_NAME} --dbname market --command="SELECT VERSION();"
      test: psql --echo-all --username market --dbname market --command="SELECT VERSION();"
      interval: 10s
      retries: 15
      start_period: 5s
      timeout: 20s
    # volumes:
      # - /home/user/db_data:/var/lib/postgresql/data
      # - /home/user/init_files:/docker-entrypoint-initdb.d/
