package com.myapps.apijava.enums;

import lombok.Getter;

@Getter
public enum PermissionData {
  ROLE_ADMIN("ADMIN"),
  ROLE_MANAGER("MANAGER"),
  ROLE_EMPLOYEE("EMPLOYEE"),
  AUTHORITY_ACCESS_ALL_USER_DATA("ACCESS_ALL_USER_DATA"),
  AUTHORITY_MODIFY_SYSTEM_SETTINGS("MODIFY_SYSTEM_SETTINGS"),
  AUTHORITY_VIEW_TEAM_REPORTS("VIEW_TEAM_REPORTS"),
  AUTHORITY_APPROVE_LEAVE_REQUESTS("APPROVE_LEAVE_REQUESTS"),
  AUTHORITY_ACCESS_SELF_RECORDS("ACCESS_SELF_RECORDS"),
  AUTHORITY_SUBMIT_SERVICE_REQUEST("SUBMIT_SERVICE_REQUEST");

  private final String name;
  PermissionData(String name) {
    this.name = name;
  }

}
