app.openapi.server-url: http://localhost:8080/api

server:
  port: 8080
  servlet.context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: market
    password: market
    driver-class-name: org.postgresql.Driver
  flyway:
    out-of-order: true
    enabled: true

hibernate:
  show_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.SQL: TRACE
    org.hibernate.type: DEBUG