app:
  openapi.server-url: http://localhost:8080/api
  security:
    secret-key: 28472B4B6150645367566B5970337336763979244226452948404D6351655468
    token-expiration-hours: 24

server:
  port: 8080
  servlet.context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: market
    password: market
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  flyway:
    out-of-order: true
    enabled: true

logging:
  level:
    org.hibernate.SQL: ERROR
#    org.hibernate.SQL: TRACE
    org.hibernate.type: ERROR