app:
  security:
    secret-key: MjQ3ODhiMzcwZTE2ZTI4OTM0NTNjM2Y4NzFlMTI3YzNkOGQ0MWIwYTBmNTZjMmIyMjJiZTRmZjk5MjMyZTUwYg==
    token:
      expiration-hours: 1
      prefix: Bearer

server:
  port: 8081
  servlet.context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgresdb
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  flyway:
    out-of-order: true
    enabled: true

logging:
  level:
    org.hibernate.SQL: ERROR
    #    org.hibernate.SQL: TRACE
    org.hibernate.type: ERROR
